### PR TITLE
Japanese Translation

### PR DESCRIPTION
**Pull request by ITotalJustice**
Corrected Japanese translation

see #7

### CODE REVIEW

**Comment by ITotalJustice** [comment]
@HoRy205 there is another translation done here https://github.com/ITotalJustice/sphaira/pull/9/files is there any changes that should be merged with this? if so, let me know which ones as i can merge your changes and then select the changes from the other translation

**Comment by HoRy205** [comment]
8"Size": "容量"
44"Advanced Options": "上級者向けオプション"
55"Advanced": "高度"
79"HandHeld": "携帯モード"

**Comment by HoRy205** [comment]
yes.

**Comment by ITotalJustice** [comment]
fixes #7

**Pull request merged**
